.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. dash_qt test_dash_qt
clean: FORCE
	$(MAKE) -C .. dash_qt_clean test_dash_qt_clean
check: FORCE
	$(MAKE) -C .. test_dash_qt_check
bitcoin-qt bitcoin-qt.exe: FORCE
	 $(MAKE) -C .. dash_qt
apk: FORCE
	$(MAKE) -C .. dash_qt_apk
